In [98]:
import pandas as pd
import uproot
import cupy as cp
import boost_histogram as bh
import numpy as np
import time
import random

In [72]:
def no_DN (frame):
    
    i = frame.index[0][0]
    new_frame = frame.loc[(frame['isDN'].values == False) & (frame['hitTime'].values < 300)]
    return new_frame.loc[i]

In [73]:
def first (frame):
    frame_sort = frame.sort_values(['hitTime'])
    frame_first = frame_sort.drop_duplicates(subset='pmtID', keep='first')
    frame_last = frame_first.sort_values('hitTime', ascending=False)
    return frame_last

In [74]:
def normal_ft(ev):
    
    mi = ev['hitTime'].min()
    
    a = ev['nHits'].values
    b = ev['pmtID'].values
    c = ev['hitTime'] - mi
    data = {'nHits': a, 'pmtID': b, 'hitTime': c}
        
    norm = pd.DataFrame(data)
    return norm

In [75]:
def save_hist (data, info, n, pre, b):
    
    dst_dir = '/home/centos/prova_E/E8_RE/'
    
    #hist = bh.Histogram(bh.axis.Regular(np.logspace(0, 300, 20), 0, 300))
    
    for i in info['evtID']:
        name = pre+str(i)+'_'+str(b)+'.npy'
        ev = data.pandas.df(entrystart=i, entrystop=i+1)
        try:
            ev_noDN = no_DN(ev)
        except:
            print(i, ': solo dark noise')
            continue
        ev_first = first(ev_noDN)
        ev_norm = normal_ft(ev_first)
        ev_time= ev_norm['hitTime'].values
        #hist.fill(ev_time)
        #array = hist.to_numpy()
        array = np.histogram(ev_time,  bins=np.logspace(np.log10(0.1), np.log10(300), 20))
        time = array[0]
        
        E_true = info['E'].loc[i]
        E = random.gauss(E_true, 0.03*np.sqrt(E_true))
        timeE = np.append(time, E)
        
        R_treu = info['R'].loc[i]
        R = random.gauss(R_true, 10)
        result = np.append(timeE, R)
        
        cp.save(dst_dir + name, result)
        #hist.reset()
        #return time

In [76]:
def call_all (file, a):
    
    data_file = uproot.open(file)
    INFO = data_file['true_info'].pandas.df()
    DATA = data_file["lpmt_hits"]
    
    if file.startswith('/home/centos/FlatComplete'):
        name = 'pos'
        
        INFO_E8 = INFO.loc[(INFO['E'] > 8) & (INFO['E'] < 9) ]
        
    elif file.startswith('/home/centos/ElectronDataset'):
        name = 'el'
        
        INFO_E8 = INFO.loc[(INFO['E'] > 9) & (INFO['E'] < 10) ]
        
    else:
        print('file non riconosciuto')
        
    save_hist(DATA, INFO_E8, 8, name, a)

In [77]:
P0 = "/home/centos/FlatComplete/eplus_hits_dn_0.root"
P1 = "/home/centos/FlatComplete/eplus_hits_dn_1.root"
P2 = "/home/centos/FlatComplete/eplus_hits_dn_2.root"
P3 = "/home/centos/FlatComplete/eplus_hits_dn_3.root"
P4 = "/home/centos/FlatComplete/eplus_hits_dn_4.root"
P5 = "/home/centos/FlatComplete/eplus_hits_dn_5.root"
P6 = "/home/centos/FlatComplete/eplus_hits_dn_6.root"
P7 = "/home/centos/FlatComplete/eplus_hits_dn_7.root"
P8 = "/home/centos/FlatComplete/eplus_hits_dn_8.root"
P9 = "/home/centos/FlatComplete/eplus_hits_dn_9.root"

In [78]:
E0 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_0.root"
E1 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_1.root"
E2 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_2.root"
E3 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_3.root"
E4 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_4.root"
E5 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_5.root"
E6 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_6.root"
E7 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_7.root"
E8 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_8.root"
E9 = "/home/centos/ElectronDataset/Hits/eminus_hits_dn_9.root"

In [79]:
time.strftime("%H") +":"+ time.strftime("%M")

'16:45'

In [80]:
call_all(P0, 0)
call_all(E0, 0)
time.strftime("%H") +":"+ time.strftime("%M")

'17:14'

In [97]:
call_all(P1, 1)
call_all(E1, 1)
time.strftime("%H") +":"+ time.strftime("%M")

AttributeError: 'numpy.ndarray' object has no attribute 'strftime'

In [99]:
call_all(P2, 2)
call_all(E2, 2)
time.strftime("%H") +":"+ time.strftime("%M")

'20:44'

In [100]:
call_all(P3, 3)
call_all(E3, 3)
time.strftime("%H") +":"+ time.strftime("%M")

'21:12'

In [101]:
call_all(P4, 4)
call_all(E4, 4)
time.strftime("%H") +":"+ time.strftime("%M")

'21:40'

In [102]:
call_all(P5, 5)
call_all(E5, 5)
time.strftime("%H") +":"+ time.strftime("%M")

'22:07'

In [103]:
call_all(P6, 6)
call_all(E6, 6)
time.strftime("%H") +":"+ time.strftime("%M")

'22:34'

In [104]:
call_all(P7, 7)
call_all(E7, 7)
time.strftime("%H") +":"+ time.strftime("%M")

'23:02'

In [105]:
call_all(P8, 8)
call_all(E8, 8)
time.strftime("%H") +":"+ time.strftime("%M")

'23:30'

In [106]:
call_all(P9, 9)
call_all(E9, 9)
time.strftime("%H") +":"+ time.strftime("%M")

'23:59'

# --------------------------------------------

In [33]:
data_file = uproot.open(P8)
info = data_file['true_info'].pandas.df()
data = data_file["lpmt_hits"]

In [11]:
INFO

evtID         E             x             y             z             R
entry                                                                         
0          0  1.611782  10070.713867   5642.622559  -1902.200195  11699.437500
1          1  1.061550   3195.711426   -438.007385  -3775.261719   4965.583984
2          2  9.552167   2571.991943    -24.381102 -17280.189453  17470.566406
3          3  8.676808  -8391.572266  -1259.657837  10496.677734  13497.609375
4          4  7.571971  14094.770508  -5504.564941   2110.553223  15277.998047
...      ...       ...           ...           ...           ...           ...
99995  99995  8.284369   2374.231934 -10126.605469  12136.030273  15983.376953
99996  99996  8.527157   8105.803711   7404.710449   3286.964355  11460.276367
99997  99997  1.110695   4506.581055  -1017.060120      4.655399   4619.924805
99998  99998  4.059003  -3667.033691   8596.628906    245.721252   9349.306641
99999  99999  1.877084 -12651.076172   8442.206055   2566.728760  15424.288086

[100000 rows x 6 columns]

In [90]:
i=0
ev = data.pandas.df(entrystart=i, entrystop=i+1)
try:
    ev_noDN = no_DN(ev)
except:
    print(i, ': solo dark noise')
            #continue
ev_first = first(ev_noDN)
ev_norm = normal_ft(ev_first)
ev_time= ev_norm['hitTime'].values
        #hist.fill(ev_time)
        #array = hist.to_numpy()
array = np.histogram(ev_time,  bins=np.logspace(np.log10(0.1), np.log10(300), 20))
time = array[0]
        
E_true = info['E'].loc[i]
E = random.gauss(E_true, 0.03*np.sqrt(E_true))
timeE = np.append(time, E)
        
R_true = info['R'].loc[i]
R = random.gauss(R_true, 10)
R = R/1000
result = np.append(timeE, R)

In [91]:
result

array([  0.        ,   1.        ,   1.        ,   0.        ,
         0.        ,   3.        ,   1.        ,  11.        ,
        19.        ,  60.        ,  86.        , 129.        ,
       214.        , 296.        , 409.        , 435.        ,
       477.        , 219.        ,  69.        ,   1.61341587,
        11.68968321])

In [63]:
timeE = np.delete(result, 20)

In [65]:
time = np.delete(timeE, 19)

In [66]:
time

array([  0.,   1.,   1.,   0.,   0.,   3.,   1.,  11.,  19.,  60.,  86.,
       129., 214., 296., 409., 435., 477., 219.,  69.])

In [81]:
E = result[19:]

In [82]:
E

array([ 1.56552574, 11.70792964])

In [83]:
R = result[:19]

In [84]:
R

array([  0.,   1.,   1.,   0.,   0.,   3.,   1.,  11.,  19.,  60.,  86.,
       129., 214., 296., 409., 435., 477., 219.,  69.])

In [92]:
result = np.reshape(result, (21, 1))

In [93]:
result.shape

(21, 1)

In [96]:
result[:19]

array([[  0.],
       [  1.],
       [  1.],
       [  0.],
       [  0.],
       [  3.],
       [  1.],
       [ 11.],
       [ 19.],
       [ 60.],
       [ 86.],
       [129.],
       [214.],
       [296.],
       [409.],
       [435.],
       [477.],
       [219.],
       [ 69.]])